index.html

Added Interstellar movie on the movie list  for hacktoberfest..

Added a new movie on the list

---

index.css
index.html

Hey @Anikkkkettt I just added a Footer to the website, you can check that out!

Footer added

---

index.html

entered a movie card

---

index.css
index.html

Font changed and the Footer wasn't responsive, and I made it responsive.

Font changed and Responsive Footer

---

index.html

I have added my favourite movie. Please merge this PR and do put the labels hacktoberfest-accepted before that.

Added my favourite movie.

---

index.html

Updated index.html with new movie

---

index.html

solved issue #17 : Fix Bug for Man Steel Movie Card

Added a card successfully and solved the issue of Man Steel movie card

---

index.html

Hey, I just fixed all the bugs in code, there were a lot of bugs, but finally I found it and solved it.
**Note: Next time before merging a pull request, see what the contributor added and changed, because there are some people that just want to destroy the code.**

Bugs fixed in code

---

index.html

Hey I just fixed the bugs (issue #32) and formatted the code to be better to read

Fixed bugs and formated code

---

index.html

Reverts Anikkkkettt/MovieHub#34

Revert "Fixed bugs and formated code"

---

index.html

Some images weren't showing up because their URL was wrong. I fixed it

Add movie images

---

index.html

Reverts Anikkkkettt/MovieHub#35

Revert "Add movie images"

---

index.html

Added new movie

---

index.html

Added Dangal movie

---

index.html

Some of the Posters URLs were not working and some were not of same sizes .

Updated poster URLs

---

index.html

add 777 charlie as my fav movie

---

.vscode/settings.json
index.html

Added a new movie card, Dune (2021)

Added Dune (2021)

---

index.html

Added a Movie Card - Avatar

---

index.html

@Anikkkkettt  I have just added "Joker" movie card. please merge it .

Added MOvie card : Joker 

---

index.html

I have added a movie card . Pather Panchali:By Satyajit Ray.
Please merge it.

Added a movie card in HTML

---

index.html

I added my movie name and details

movie name added

---

index.html

added my pr sayak

---

index.html

I have added new movie to the repository.

Added new movie: The Hobbit

---

index.html

i'll waiting for your response to my pull request. thankyou

Berlian contribute to moviehub

---

index.html

CristinaEU1

---

index.html

Added movie black adam
pls merge my pr under hactoberfest22

Added movie Black Adam
